version: "3.1"

services:
  www:
    build: .
    ports:
      - "8004:80"
    volumes:
      - ./Src:/var/www/html/
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - default
  database:
    container_name: database
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - my-db:/var/lib/mysql
      - ./Tests/Database/:/docker-entrypoint-initdb.d
    networks:
      - default

volumes:
  my-db:
