name: Copy Secrets to Dependabot

on:
  issue_comment:
    types: [created]

jobs:
  copy-secrets:
    runs-on: ubuntu-latest
    if: |
      github.event.comment.body == '@gstraccini copy secrets dependabot' ||
      startsWith(github.event.comment.body, '@gstraccini copy secret dependabot')
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run secret copy script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        node .github/scripts/copy-secrets.js

    - name: Handle errors
      if: failure()
      run: echo "Error occurred during secret copying process"

    - name: Success message
      if: success()
      run: echo "Secrets copied successfully to Dependabot"
