name: Deploy via ftp

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy service to FTP
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - "Src/**"

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1
        with:
          versionSpec: "5.x"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1
        with:
          useConfigFile: true

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        uses: "php-actions/composer@v6"
        with:
          php_extensions: sockets
          dev: no
          progress: yes
          working_dir: "./Src/"

      - name: Create .htaccess secrets file
        if: ${{ steps.changes.outputs.src == 'true' }}
        run: |
          cd Src
          mkdir -p secrets
          cd secrets
          echo "Deny from all" >> .htaccess
      
      - name: Generate AppVeyor secrets file
        if: ${{ steps.changes.outputs.src == 'true' }}
        run: |
          cd Src
          mkdir -p secrets
          cd secrets
          echo "<?php" >> appVeyor.secrets.php
          echo "\$appVeyorKey = \"${{ secrets.APPVEYOR_KEY }}\";" >> appVeyor.secrets.php

      - name: Generate GitHub App secrets file
        if: ${{ steps.changes.outputs.src == 'true' }}
        run: |
          cd Src
          mkdir -p secrets
          cd secrets
          echo "<?php" >> gitHubApp.secrets.php
          echo "\$gitHubUserToken        = \"${{ secrets.USER_TOKEN }}\";" >> gitHubApp.secrets.php
          echo "\$gitHubAppId            = \"${{ secrets.APP_ID }}\";" >> gitHubApp.secrets.php
          echo "\$gitHubAppPrivateKey    = \"${{ secrets.APP_PRIVATE_KEY}}\";" >> gitHubApp.secrets.php
          echo "\$gitHubWebhookEndpoint  = \"${{ secrets.WEBHOOK_ENDPOINT }}\";" >> gitHubApp.secrets.php
          echo "\$gitHubWebhookSignature = \"${{ secrets.WEBHOOK_SIGNATURE }}\";" >> gitHubApp.secrets.php

      - name: Generate HealthChecksIo secrets file
        if: ${{ steps.changes.outputs.src == 'true' }}
        run: |
          cd Src
          mkdir -p secrets
          cd secrets
          echo "<?php" >> healthChecksIo.secrets.php
          echo "\$healthChecksIoBranches     = \"${{ secrets.HEALTHCHECKSIO_BRANCHES }}\";" >> healthChecksIo.secrets.php
          echo "\$healthChecksIoIssues       = \"${{ secrets.HEALTHCHECKSIO_ISSUES }}\";" >> healthChecksIo.secrets.php
          echo "\$healthChecksIoComments     = \"${{ secrets.HEALTHCHECKSIO_COMMENTS }}\";" >> healthChecksIo.secrets.php
          echo "\$healthChecksIoCPushes      = \"${{ secrets.HEALTHCHECKSIO_PUSHES }}\";" >> healthChecksIo.secrets.php
          echo "\$healthChecksIoPullRequests = \"${{ secrets.HEALTHCHECKSIO_PULL_REQUESTS }}\";" >> healthChecksIo.secrets.php
          echo "\$healthChecksIoSignature    = \"${{ secrets.HEALTHCHECKSIO_SIGNATURE }}\";" >> healthChecksIo.secrets.php

      - name: Create Logger secrets file
        if: ${{ steps.changes.outputs.src == 'true' }}
        run: |
          cd Src
          mkdir -p secrets
          cd secrets
          echo "<?php" >> logger.secrets.php
          echo "\$loggerUrl      = \"${{ secrets.LOGGER_URL }}\";" >> logger.secrets.php
          echo "\$loggerApiKey   = \"${{ secrets.LOGGER_APIKEY }}\";" >> logger.secrets.php
          echo "\$loggerApiToken = \"${{ secrets.LOGGER_APITOKEN }}\";" >> logger.secrets.php
      
      - name: Create MySQL secrets file
        if: ${{ steps.changes.outputs.src == 'true' }}
        run: |
          cd Src
          mkdir -p secrets
          cd secrets
          echo "<?php" >> mySql.secrets.php
          echo "\$mySqlHost     = \"127.0.0.1\";" >> mySql.secrets.php
          echo "\$mySqlUser     = \"${{ secrets.MYSQL_USER }}\";" >> mySql.secrets.php
          echo "\$mySqlPassword = \"${{ secrets.MYSQL_PASSWORD }}\";" >> mySql.secrets.php
          echo "\$mySqlDatabase = \"${{ secrets.MYSQL_DATABASE }}\";" >> mySql.secrets.php

      - name: Create RabbitMQ secrets file
        if: ${{ steps.changes.outputs.src == 'true' }}
        run: |
          cd Src
          mkdir -p secrets
          cd secrets
          echo "<?php" >> rabbitMq.secrets.php
          echo "\$rabbitMqHost     = \"${{ secrets.RABBITMQ_HOST }}\";" >> rabbitMq.secrets.php
          echo "\$rabbitMqPort     = ${{ secrets.RABBITMQ_PORT }};" >> rabbitMq.secrets.php
          echo "\$rabbitMqUser     = \"${{ secrets.RABBITMQ_USER }}\";" >> rabbitMq.secrets.php
          echo "\$rabbitMqPassword = \"${{ secrets.RABBITMQ_PASSWORD }}\";" >> rabbitMq.secrets.php
          echo "\$rabbitMqVhost    = \"${{ secrets.RABBITMQ_VHOST }}\";" >> rabbitMq.secrets.php

      - name: Upload service
        if: ${{ steps.changes.outputs.src == 'true' }}
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "Src"
          remoteDir: "/"

  create_release:
    name: Create release
    needs: deploy
    env:
      SEMVER: ${{ needs.deploy.outputs.semVer }}
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: false
          skipIfReleaseExists: true
          draft: false
          makeLatest: true
          tag: v${{ env.SEMVER }}
          name: Release v${{ env.SEMVER }}
          generateReleaseNotes: true
          body: Release ${{ env.SEMVER }} of ${{ github.event.repository.name }}
