name: Issue Detection

on: [push]

jobs:
  issue-detection:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygithub
    - name: Run pre-commit hook
      run: |
        chmod +x .githooks/pre-commit
        ./.githooks/pre-commit
    - name: Create issues for detected comments
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python .github/scripts/create_issues.py